[tool.poetry]
name = "aqi-prediction-mlops"
version = "0.1.0"
description = "An MlOps project for AQI prediction"
authors = ["Yassine El Azhari"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
